<a href="https://colab.research.google.com/github/nayvti380/Data-Science/blob/main/Data_Science_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = r'https://raw.githubusercontent.com/rafaelpuyau/infinity_school/main/ds/datasets/wines.csv'

In [ ]:
df = pd.read_csv(data)

In [ ]:
df.head(3)

date   label  vintage   style   country   price  quantity  rate
0  2021-01-04  Wine K     2002   White  Portugal  144.22         9    97
1  2021-03-11  Wine J     1982     Red  Portugal  244.80         3    76
2  2021-10-02  Wine Y     2018  Orange    France   98.83         2    79

In [ ]:
df['style'].unique()

array(['White', 'Red', 'Orange', 'Sparkling', 'Rose', 'Sweet'],
      dtype=object)

In [ ]:
df['style'].value_counts()

style
White        1710
Rose         1706
Orange       1658
Sweet        1648
Red          1640
Sparkling    1638
Name: count, dtype: int64

In [ ]:
df['quantity'].max()

15

In [ ]:
df['date'] = pd.to_datetime(df['date'])

In [ ]:
df['style'].value_counts().head()

style
White     1710
Rose      1706
Orange    1658
Sweet     1648
Red       1640
Name: count, dtype: int64

In [ ]:
df[["label", "price"]].sort_values("price", ascending=False).head(1)

label    price
1249  Wine Q  1107.89

In [ ]:
df[["style", "price"]].sort_values("price", ascending=True).head(1)

style  price
9256  Sweet  50.01

In [ ]:
vetor = np.array([1,2,3,4,5,6,7,8,9,10])
vetor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
vetor+3

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
vetor*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
vetor**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [ ]:
np.power(vetor,3)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [ ]:
np.sqrt(vetor)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [ ]:
vetor**(1/2)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [ ]:
np.arange(5,21,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
a = np.array([5,10,15,20])
a

array([ 5, 10, 15, 20])

In [ ]:
b = np.arange(1,6,1)
b

array([1, 2, 3, 4, 5])

In [ ]:
df

date   label  vintage   style   country   price  quantity  rate
0     2021-01-04  Wine K     2002   White  Portugal  144.22         9    97
1     2021-03-11  Wine J     1982     Red  Portugal  244.80         3    76
2     2021-10-02  Wine Y     2018  Orange    France   98.83         2    79
3     2021-06-05  Wine I     1989     Red     Spain   59.64        11    77
4     2021-09-06  Wine N     2006   White     Spain  187.70         6    91
...          ...     ...      ...     ...       ...     ...       ...   ...
9995  2021-08-07  Wine S     1983    Rose    France  264.69         6    89
9996  2021-03-03  Wine S     1994    Rose     Spain   55.84         4   100
9997  2021-12-28  Wine N     2001   White  Portugal  137.79        13    96
9998  2021-06-19  Wine T     1988    Rose     Italy  100.29         9    83
9999  2021-09-18  Wine V     1982   Sweet  Portugal   63.85        13   100

[10000 rows x 8 columns]

In [ ]:
df.iloc[0:1001,2:6]

vintage      style   country   price
0        2002      White  Portugal  144.22
1        1982        Red  Portugal  244.80
2        2018     Orange    France   98.83
3        1989        Red     Spain   59.64
4        2006      White     Spain  187.70
...       ...        ...       ...     ...
996      2020  Sparkling     Italy   50.37
997      2013  Sparkling   Germany  285.28
998      1996       Rose     Chile   55.53
999      1999  Sparkling     Chile  171.81
1000     2007      White   Uruguay  191.26

[1001 rows x 4 columns]

In [ ]:
df.sort_values("vintage")

date   label  vintage      style    country   price  quantity  \
3234  2021-02-10  Wine X     1982      Sweet   Portugal  356.93        12   
3193  2021-03-15  Wine S     1982       Rose    Uruguay  242.38        11   
3115  2021-01-18  Wine N     1982      White  Argentina  400.47         9   
9999  2021-09-18  Wine V     1982      Sweet   Portugal   63.85        13   
8697  2021-01-08  Wine Q     1982  Sparkling        USA  270.38         2   
...          ...     ...      ...        ...        ...     ...       ...   
1897  2021-03-23  Wine Y     2021     Orange      Spain  218.88         2   
5574  2021-01-06  Wine Z     2021     Orange      Chile  358.34         9   
1886  2021-05-27  Wine Y     2021     Orange   Portugal  502.35         6   
5548  2021-03-11  Wine P     2021  Sparkling    Germany  303.76         3   
3257  2021-10-19  Wine N     2021      White        USA   55.30        11   

      rate  
3234    95  
3193   100  
3115   100  
9999   100  
8697    93  
...    ...  
1897    84  
5574    81  
1886    76  
5548    92  
3257    91  

[10000 rows x 8 columns]

from matplotlib import pyplot as plt
_df_0['vintage'].plot(kind='hist', bins=20, title='vintage')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['price'].plot(kind='hist', bins=20, title='price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['quantity'].plot(kind='hist', bins=20, title='quantity')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['rate'].plot(kind='hist', bins=20, title='rate')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('style').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_5.plot(kind='scatter', x='vintage', y='price', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='price', y='quantity', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='quantity', y='rate', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['price']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('style')):
  _plot_series(series, series_name, i)
  fig.legend(title='style', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('price')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['quantity']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('style')):
  _plot_series(series, series_name, i)
  fig.legend(title='style', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('quantity')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['rate']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('style')):
  _plot_series(series, series_name, i)
  fig.legend(title='style', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('rate')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['date']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'date'}, axis=1)
              .sort_values('date', ascending=True))
  xs = counted['date']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('style')):
  _plot_series(series, series_name, i)
  fig.legend(title='style', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_12['vintage'].plot(kind='line', figsize=(8, 4), title='vintage')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_13['price'].plot(kind='line', figsize=(8, 4), title='price')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_14['quantity'].plot(kind='line', figsize=(8, 4), title='quantity')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['rate'].plot(kind='line', figsize=(8, 4), title='rate')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_16['style'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_16, x='vintage', y='style', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_17['style'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_17, x='price', y='style', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_18['style'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_18, x='quantity', y='style', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_19['style'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_19, x='rate', y='style', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
df.head()

date   label  vintage   style   country   price  quantity  rate
0  2021-01-04  Wine K     2002   White  Portugal  144.22         9    97
1  2021-03-11  Wine J     1982     Red  Portugal  244.80         3    76
2  2021-10-02  Wine Y     2018  Orange    France   98.83         2    79
3  2021-06-05  Wine I     1989     Red     Spain   59.64        11    77
4  2021-09-06  Wine N     2006   White     Spain  187.70         6    91

from matplotlib import pyplot as plt
_df_35['vintage'].plot(kind='hist', bins=20, title='vintage')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_36['price'].plot(kind='hist', bins=20, title='price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_37['quantity'].plot(kind='hist', bins=20, title='quantity')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_38['rate'].plot(kind='hist', bins=20, title='rate')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_39.groupby('date').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_40.groupby('label').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_41.groupby('style').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_42.groupby('country').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_43.plot(kind='scatter', x='vintage', y='price', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_44.plot(kind='scatter', x='price', y='quantity', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_45.plot(kind='scatter', x='quantity', y='rate', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['vintage']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_46.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('date')):
  _plot_series(series, series_name, i)
  fig.legend(title='date', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('vintage')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['vintage']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_47.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('label')):
  _plot_series(series, series_name, i)
  fig.legend(title='label', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('vintage')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['vintage']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_48.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('style')):
  _plot_series(series, series_name, i)
  fig.legend(title='style', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('vintage')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['date']
  ys = series['vintage']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_49.sort_values('date', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('country')):
  _plot_series(series, series_name, i)
  fig.legend(title='country', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date')
_ = plt.ylabel('vintage')

from matplotlib import pyplot as plt
_df_50['vintage'].plot(kind='line', figsize=(8, 4), title='vintage')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_51['price'].plot(kind='line', figsize=(8, 4), title='price')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_52['quantity'].plot(kind='line', figsize=(8, 4), title='quantity')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_53['rate'].plot(kind='line', figsize=(8, 4), title='rate')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['label'].value_counts()
    for x_label, grp in _df_54.groupby('date')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('date')
_ = plt.ylabel('label')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['style'].value_counts()
    for x_label, grp in _df_55.groupby('label')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('label')
_ = plt.ylabel('style')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['country'].value_counts()
    for x_label, grp in _df_56.groupby('style')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('style')
_ = plt.ylabel('country')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_57['date'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_57, x='vintage', y='date', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_58['label'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_58, x='vintage', y='label', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_59['style'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_59, x='vintage', y='style', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_60['country'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_60, x='vintage', y='country', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
df.loc[((df["style"] == "Red")) & (df['rate']>=90)]

date   label  vintage style    country   price  quantity  rate
6     2021-11-01  Wine A     2003   Red        USA  464.32         9    99
17    2021-04-22  Wine G     2018   Red        USA  410.45         7    98
27    2021-07-14  Wine E     1983   Red      Chile  306.10        15    99
45    2021-11-06  Wine H     2005   Red    Germany  226.67         3    90
54    2021-08-27  Wine B     1985   Red   Portugal  227.87         9    99
...          ...     ...      ...   ...        ...     ...       ...   ...
9952  2021-10-14  Wine I     2015   Red    Uruguay  246.65         3    99
9956  2021-04-15  Wine F     1989   Red     Brazil   90.48        15    90
9970  2021-06-12  Wine F     2001   Red  Argentina  298.45         3    97
9982  2021-11-03  Wine B     2015   Red      Chile   83.89         3    97
9985  2021-06-18  Wine I     1988   Red      Chile  164.67         6    93

[669 rows x 8 columns]

In [ ]:
df.loc[((df["style"] == "Red")) ^ (df['rate']>=90)]

date   label  vintage      style    country   price  quantity  \
0     2021-01-04  Wine K     2002      White   Portugal  144.22         9   
1     2021-03-11  Wine J     1982        Red   Portugal  244.80         3   
3     2021-06-05  Wine I     1989        Red      Spain   59.64        11   
4     2021-09-06  Wine N     2006      White      Spain  187.70         6   
8     2021-03-06  Wine R     2007  Sparkling  Argentina  178.77        14   
...          ...     ...      ...        ...        ...     ...       ...   
9993  2021-05-21  Wine T     1988       Rose   Portugal  262.82        12   
9994  2021-06-27  Wine U     2007       Rose      Italy  112.68         1   
9996  2021-03-03  Wine S     1994       Rose      Spain   55.84         4   
9997  2021-12-28  Wine N     2001      White   Portugal  137.79        13   
9999  2021-09-18  Wine V     1982      Sweet   Portugal   63.85        13   

      rate  
0       97  
1       76  
3       77  
4       91  
8       96  
...    ...  
9993    96  
9994    95  
9996   100  
9997    96  
9999   100  

[4520 rows x 8 columns]

In [ ]:
df.loc[((df["style"] == "Red") & (df['rate']>=90))|((df['style'] == 'White')&(df['rate']>=80))]

date   label  vintage  style   country   price  quantity  rate
0     2021-01-04  Wine K     2002  White  Portugal  144.22         9    97
4     2021-09-06  Wine N     2006  White     Spain  187.70         6    91
6     2021-11-01  Wine A     2003    Red       USA  464.32         9    99
14    2021-08-12  Wine L     1985  White     Italy   73.44         5    82
15    2021-11-20  Wine N     2006  White       USA  785.10         2    83
...          ...     ...      ...    ...       ...     ...       ...   ...
9982  2021-11-03  Wine B     2015    Red     Chile   83.89         3    97
9983  2021-07-17  Wine L     1995  White    Brazil  102.18        11    90
9985  2021-06-18  Wine I     1988    Red     Chile  164.67         6    93
9987  2021-09-04  Wine O     1987  White    France   97.65        15    89
9997  2021-12-28  Wine N     2001  White  Portugal  137.79        13    96

[2049 rows x 8 columns]